### ISSUE TITLE
ver 3.0.0 doesn't show results with capitalized letters

### ISSUE THREAD

**Issue by takenp** [step-/find-n-run#20]
### Title

 * ver 3.0.0 doesn't show results with capitalized letters

### System Info

 * Findnrun version - 3.0.0
 * Linux OS type and version - tahrpuppy 6.0.2
 * Puppy Linux puplet name and version
 * mdview version - command line `mdview` to find out
 * System language - ru_RU
 * Is findnrun NLS package installed? -- no

**Comment by step-** [comment]
The following text received from @takenp via e-mail:

>If I use small letters it searches OK but fails with any capitalized ones
>for example: abiw -- ok, Abiw -- nothing
>
>checked with 1.0 version -- no problem

**Comment by step-** [comment]
Can you please try setting
```sh
    CASEDEPENDENT=true
```
in file `~/.findnrunrc`

`CASEDEPENDENT` was introduced in version 2.0.0. It's a hidden setting, meaning that there is no GUI for it. Only the main settings get a GUI.  All settings and more are documented in the help file, but perhaps it isn't installed in tahrpuppy 6.0.2 ?
Here's a link to the [help file](../tree/master/usr/share/doc/findnrun/index.md), once you visit the page click  the **User Preferences** link.
